### ISSUE TITLE
Replace auto-indent-mode

### ISSUE THREAD

**Issue by jeffvalk** [jeffvalk/snap-indent#1]
### Rationale

[auto-indent-mode][aim] has interoperability bugs with common packages (including [company][company], [swiper][swiper], [beacon][beacon], [smooth-scrolling][smooth] and others) that have remained unaddressed for years. Certain bugs have popped up [again][args41] and [again][args69] dating back a [decade][args6]. The package is surprisingly complex (2655 lines of code), uses long-[deprecated][cl] dependencies, relies on adding [advice][advice] to core functions, and [disables][electric] a built-in package. Attempts to patch [existing][existing] issues seem to cause [new][new] ones.

I am grateful to auto-indent-mode's author(s) for a useful tool that I utilized for years. However, the current state of things suggests it's time to move on. 

### Solution

Retire auto-indent-mode in favor of something simpler and more hygienic: [snap-indent][snap] indents on yank/paste and (optionally) save. It is minimalist, flexible, and plays well with other packages.

`snap-indent` pairs nicely with `electric-indent-mode`, which indents while typing. The latter has been built-in and enabled by default since Emacs 24.

[aim]: https://github.com/mattfidler/auto-indent-mode.el
[snap]: https://github.com/jeffvalk/snap-indent

[company]: https://github.com/mattfidler/auto-indent-mode.el/issues/65
[swiper]: https://github.com/mattfidler/auto-indent-mode.el/issues/65
[smooth]: https://github.com/mattfidler/auto-indent-mode.el/issues/66
[beacon]: https://github.com/mattfidler/auto-indent-mode.el/issues/70

[args6]: https://github.com/mattfidler/auto-indent-mode.el/issues/6
[args41]: https://github.com/mattfidler/auto-indent-mode.el/issues/41
[args69]: https://github.com/mattfidler/auto-indent-mode.el/issues/69

[cl]: https://github.com/mattfidler/auto-indent-mode.el/issues/67
[advice]: https://github.com/mattfidler/auto-indent-mode.el/issues/25

[electric]: https://github.com/mattfidler/auto-indent-mode.el/issues/60
[existing]: https://github.com/mattfidler/auto-indent-mode.el/issues/62
[new]: https://github.com/mattfidler/auto-indent-mode.el/issues/63

**Comment by anoduck** [comment]
Found snap-indent through [auto-indent-mode issue #69](https://github.com/mattfidler/auto-indent-mode.el/issues/69). Keep up the good work @jeffvalk

**Comment by jeffvalk** [comment]
My sincere thanks to @mattfidler, author of `auto-indent-mode`, who retired that package on 2023-06-23 and [recommended](https://github.com/mattfidler/auto-indent-mode.el/commit/2dab3cb2229687b16c8a3aca3f8063df2275b8ea) snap-indent.
